-- drop tables if the already exist
drop table cashflow if exists;
drop table cashflow_item if exists;
drop table depot if exists;
drop table document_type if exists;
drop table fruit if exists;
drop table inventory if exists;
drop table product if exists;
drop table product_fruit if exists;
drop table product_fruit_price if exists;
drop table stocktake if exists;

-- create tables
create table cashflow (period varchar(255) not null, date_created timestamp not null, date_updated timestamp, deleted boolean not null, credits double not null, debits double not null, previous_balance double not null, primary key (period));
create table cashflow_item (id bigint generated by default as identity, date_created timestamp not null, date_updated timestamp, deleted boolean not null, description varchar(255), document_number varchar(255) not null, item_date timestamp not null, type varchar(255), value double, document_type_id bigint, primary key (id));
create table depot (id bigint generated by default as identity, date_created timestamp not null, date_updated timestamp, deleted boolean not null, keep_stock boolean not null, name varchar(255) not null, primary key (id));
create table document_type (id bigint generated by default as identity, date_created timestamp not null, date_updated timestamp, deleted boolean not null, name varchar(255) not null, primary key (id));
create table fruit (id bigint generated by default as identity, date_created timestamp not null, date_updated timestamp, deleted boolean not null, harvest varchar(255), initials varchar(255) not null, name varchar(255) not null, primary key (id));
create table inventory (period varchar(255) not null, date_created timestamp not null, date_updated timestamp, deleted boolean not null, initial_stock double not null, stock_in double not null, stock_out double not null, fruit_id bigint not null, depot_id bigint not null, product_id bigint not null, primary key (depot_id, fruit_id, period, product_id));
create table product (id bigint generated by default as identity, date_created timestamp not null, date_updated timestamp, deleted boolean not null, name varchar(255) not null, unit varchar(255) not null, primary key (id));
create table product_fruit (fruit_id bigint not null, product_id bigint not null, primary key (fruit_id, product_id));
create table product_fruit_price (id bigint generated by default as identity, date_created timestamp not null, date_updated timestamp, deleted boolean not null, price double not null, price_expiration_date timestamp not null, fruit_id bigint not null, product_id bigint not null, primary key (id));
create table stocktake (id bigint generated by default as identity, amount double not null, date_created timestamp not null, date_updated timestamp, deleted boolean not null, item_date timestamp not null, type integer, depot_id bigint not null, fruit_id bigint not null, product_id bigint not null, primary key (id));

-- add constraints and foreign keys
alter table depot add constraint uc_depot_name unique (name);
alter table document_type add constraint uc_doctype_name unique (name);
alter table fruit add constraint uc_fruit_name unique (name);
alter table product add constraint uc_product_name unique (name);
alter table cashflow_item add constraint FK5pvipk2fijpck092di9w7skxq foreign key (document_type_id) references document_type;
alter table inventory add constraint FKlg2gc7ovas855qu5f4wh9ckn0 foreign key (fruit_id) references fruit;
alter table inventory add constraint FKsc43kahu3c8exa5u1g5syajap foreign key (depot_id) references depot;
alter table inventory add constraint FKp7gj4l80fx8v0uap3b2crjwp5 foreign key (product_id) references product;
alter table product_fruit add constraint FKkl8s9866dx6lfifw6r5m6o81a foreign key (fruit_id) references fruit;
alter table product_fruit add constraint FKqvd1h1c6m1oekc3vqmepjvw1l foreign key (product_id) references product;
alter table product_fruit_price add constraint FKfu84brya1m81pq3vsny6asf6p foreign key (fruit_id) references fruit;
alter table product_fruit_price add constraint FKt8a8wbamorbsg8squ9l479uf1 foreign key (product_id) references product;
alter table stocktake add constraint FK216nwr4ajq1j3bpxfmkgwcrb6 foreign key (depot_id) references depot;
alter table stocktake add constraint FK2lmvt9u8g933p3rbwrp1soj3a foreign key (fruit_id) references fruit;
alter table stocktake add constraint FK5yrl51oidvqa5wuodeuc0vup0 foreign key (product_id) references product;