drop table cashflow if exists;
drop table cashflow_item if exists;
drop table document_type if exists;
drop table fruit if exists;
drop table product if exists;
drop table product_fruit if exists;
drop table product_fruit_price if exists;
drop sequence if exists hibernate_sequence;

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE cashflow
  (
     period           VARCHAR(255) NOT NULL,
     date_created     TIMESTAMP NOT NULL,
     date_updated     TIMESTAMP,
     deleted          BOOLEAN NOT NULL,
     credits          DOUBLE NOT NULL,
     debits           DOUBLE NOT NULL,
     previous_balance DOUBLE NOT NULL,
     PRIMARY KEY (period)
  );

CREATE TABLE cashflow_item
  (
     id               BIGINT NOT NULL,
     date_created     TIMESTAMP NOT NULL,
     date_updated     TIMESTAMP,
     deleted          BOOLEAN NOT NULL,
     description      VARCHAR(255),
     document_number  VARCHAR(255) NOT NULL,
     item_date        TIMESTAMP NOT NULL,
     TYPE             VARCHAR(255),
     VALUE            DOUBLE,
     document_type_id BIGINT,
     PRIMARY KEY (id)
  );

CREATE TABLE document_type
  (
     id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
     date_created TIMESTAMP NOT NULL,
     date_updated TIMESTAMP,
     deleted      BOOLEAN NOT NULL,
     name         VARCHAR(255) NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE fruit
  (
     id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
     date_created TIMESTAMP NOT NULL,
     date_updated TIMESTAMP,
     deleted      BOOLEAN NOT NULL,
     harvest      VARCHAR(255),
     initials     VARCHAR(255) NOT NULL,
     name         VARCHAR(255) NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE product
  (
     id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
     date_created TIMESTAMP NOT NULL,
     date_updated TIMESTAMP,
     deleted      BOOLEAN NOT NULL,
     name         VARCHAR(255) NOT NULL,
     unit         VARCHAR(255) NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE product_fruit
  (
     fruit_id   BIGINT NOT NULL,
     product_id BIGINT NOT NULL,
     PRIMARY KEY (fruit_id, product_id)
  );

CREATE TABLE product_fruit_price
  (
     id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
     date_created          TIMESTAMP NOT NULL,
     date_updated          TIMESTAMP,
     deleted               BOOLEAN NOT NULL,
     price                 DOUBLE NOT NULL,
     price_expiration_date TIMESTAMP NOT NULL,
     fruit_id              BIGINT NOT NULL,
     product_id            BIGINT NOT NULL,
     PRIMARY KEY (id)
  );  

 ALTER TABLE document_type
  ADD CONSTRAINT uc_doctype_name UNIQUE (name);

ALTER TABLE fruit
  ADD CONSTRAINT uc_fruit_name UNIQUE (name);

ALTER TABLE product
  ADD CONSTRAINT uc_product_name UNIQUE (name);

ALTER TABLE cashflow_item
  ADD CONSTRAINT fk_cashflow_document_type FOREIGN KEY (document_type_id)
  REFERENCES document_type;

ALTER TABLE product_fruit
  ADD CONSTRAINT fk_product_fruit_fruit FOREIGN KEY (fruit_id) REFERENCES
  fruit;

ALTER TABLE product_fruit
  ADD CONSTRAINT fk_product_fruit_product FOREIGN KEY (product_id) REFERENCES
  product;

ALTER TABLE product_fruit_price
  ADD CONSTRAINT fk_product_fruit_price_fruit FOREIGN KEY (fruit_id) REFERENCES
  fruit;

ALTER TABLE product_fruit_price
  ADD CONSTRAINT fk_product_fruit_price_product FOREIGN KEY (product_id) REFERENCES
  product;  